# TODO 기본적으로 잡혀있는 JPA 설정값은?

spring:
#  profiles:
#    include: oauth
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console